linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 200

linters:
  enable-all: true
  disable:
    - dupl
    - exhaustive
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goerr113
    - gofumpt
    - gomnd
    - lll
    - nestif
    - nlreturn
    - wrapcheck
    - wsl
    - nakedret
    - paralleltest
    - testpackage
